import {TypeRoutes} from '@type';

export const Routes: TypeRoutes = {
  Home: 'Home',
  Profile: 'Profile',
  MainLayout: 'MainLayout',
  FaceAnalytics: 'FaceAnalytics',
  RecordingInstruction: 'RecordingInstruction',
  RecordingVideo: 'RecordingVideo',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  ProfileInfo: 'ProfileInfo',
  InviteFriend: 'InviteFriend',
  Setting: 'Setting',
  Language: 'Language',
  Onboarding: 'Onboarding',
  AnalyticsResult: 'AnalyticsResult',
  ConfirmOTP: 'ConfirmOTP',
  ForgotPassword: 'ForgotPassword',
  PrivacyPolicy: 'PrivacyPolicy',
  SupportCenter: 'SupportCenter',
  ReactNaviveVideo: 'ReactNaviveVideo',
  TakePhoto: 'TakePhoto',
  Notification: 'Notification',
  AnalyticHistory: 'AnalyticHistory',
  AnalyticsResultImage: 'AnalyticsResultImage',
  NaturalBeautyTips: 'NaturalBeautyTips',
  DetailBeautyTips: 'DetailBeautyTips',
};
